import type { GuideStep } from "@/data/demoGuideSteps";
import type { PrepSession } from "@/types/prep";
import "@/styles/prep-pdf.css";

function replaceClient(text: string, name: string): string {
  return text.replace(/\[CLIENT\]/g, name).replace(/\[Lead's Name\]/gi, name);
}

function clientSlug(name: string): string {
  return name.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
}

export function prepPdfFilename(clientName: string): string {
  return `prep-${clientSlug(clientName) || "client"}.pdf`;
}

interface PrepPdfDocumentProps {
  session: PrepSession;
}

export function PrepPdfDocument({ session }: PrepPdfDocumentProps) {
  const { client, guideSteps, citedUrls } = session;
  const name = client.empresa;

  return (
    <div className="prep-pdf-root">
      <h1>{name} — Pre-Demo Preparation</h1>
      <p className="prep-pdf-meta">
        {client.industry} · {client.employeeCount} employees
        <br />
        {client.demoGoal}
      </p>

      {guideSteps.map((step) => (
        <StepSection key={step.id} step={step} clientName={name} />
      ))}

      {citedUrls.length > 0 && (
        <div className="prep-pdf-block">
          <h2>Sources</h2>
          <ul>
            {citedUrls.map((url) => (
              <li key={url}>
                <a href={url}>{url}</a>
              </li>
            ))}
          </ul>
        </div>
      )}

      <p className="prep-pdf-footer">
        Generated by Factorial Pre-Demo Prep · {new Date(session.createdAt).toLocaleDateString()}
      </p>
    </div>
  );
}

function StepSection({ step, clientName }: { step: GuideStep; clientName: string }) {
  return (
    <section className="prep-pdf-block">
      <h2>
        {step.index}. {step.title}
        {step.duration ? ` (${step.duration})` : ""}
      </h2>
      <p className="prep-pdf-meta">{replaceClient(step.subtitle, clientName)}</p>

      {step.icebreaker && (
        <div className="prep-pdf-block">
          <p className="prep-pdf-label">Warm greeting &amp; rapport</p>
          <div className="prep-pdf-quote">{replaceClient(step.icebreaker.greeting, clientName)}</div>
          <div className="prep-pdf-quote">{replaceClient(step.icebreaker.rapport, clientName)}</div>
          {step.icebreaker.framing && (
            <div className="prep-pdf-quote">{replaceClient(step.icebreaker.framing, clientName)}</div>
          )}
        </div>
      )}

      {step.businessProfile && (
        <div className="prep-pdf-block">
          <p className="prep-pdf-label">Business profile &amp; angle</p>
          <ul>
            <li>
              <strong>Industry:</strong> {step.businessProfile.industryDetail}
            </li>
            <li>
              <strong>Location:</strong> {step.businessProfile.location}
            </li>
            <li>
              <strong>Workforce:</strong> {step.businessProfile.workforceType}
            </li>
            <li>
              <strong>Core pain:</strong> {step.businessProfile.corePainPoint}
            </li>
            <li>
              <strong>Factorial angle:</strong> {step.businessProfile.factorialValueProp}
            </li>
          </ul>
        </div>
      )}

      {step.employeeCountNote && (
        <p className="prep-pdf-pain">
          <strong>Employees:</strong> {step.employeeCountNote}
        </p>
      )}

      {step.bullets && step.bullets.length > 0 && (
        <ul>
          {step.bullets.map((b) => (
            <li key={b}>{replaceClient(b, clientName)}</li>
          ))}
        </ul>
      )}

      {step.validationQuestion && step.kind !== "executiveSummary" && (
        <p className="prep-pdf-quote">
          Ask: &ldquo;{replaceClient(step.validationQuestion, clientName)}&rdquo;
        </p>
      )}

      {step.discoveryBlocks && step.discoveryBlocks.length > 0 && (
        <div>
          {step.discoveryBlocks.map((block) => (
            <div key={block.id} className="prep-pdf-block">
              <h3>{block.title}</h3>
              <p className="prep-pdf-pain">{block.painContext}</p>
              <ul>
                {block.questions.map((q) => (
                  <li key={q}>{replaceClient(q, clientName)}</li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      )}

      {step.discoveryAreas && !step.discoveryBlocks?.length && (
        <div>
          {step.discoveryAreas.map((area) => (
            <div key={area.id} className="prep-pdf-block">
              <h3>{area.title}</h3>
              {area.opener && <p className="prep-pdf-pain">&ldquo;{area.opener}&rdquo;</p>}
              <ul>
                {area.questions.map((q) => (
                  <li key={q}>{q}</li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      )}

      {step.beforeItems && step.afterItems && (
        <div className="prep-pdf-block">
          <p className="prep-pdf-label">Instead of</p>
          <ul>
            {step.beforeItems.map((i) => (
              <li key={i}>{i}</li>
            ))}
          </ul>
          <p className="prep-pdf-label">They can</p>
          <ul>
            {step.afterItems.map((i) => (
              <li key={i}>{i}</li>
            ))}
          </ul>
        </div>
      )}

      {step.demoTransition && (
        <div className="prep-pdf-block">
          <p className="prep-pdf-label">Transition to demo</p>
          <div className="prep-pdf-quote">{replaceClient(step.demoTransition, clientName)}</div>
        </div>
      )}

      {step.demoModules && step.demoModules.length > 0 && (
        <table>
          <thead>
            <tr>
              <th>Area</th>
              <th>Modules</th>
            </tr>
          </thead>
          <tbody>
            {step.demoModules.map((mod) => (
              <tr key={mod.area}>
                <td>{mod.area}</td>
                <td>{mod.modules.join(" · ")}</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}

      {step.outcomes && (
        <ul>
          {step.outcomes.map((o) => (
            <li key={o}>{replaceClient(o, clientName)}</li>
          ))}
        </ul>
      )}

      {step.questions && (
        <ul>
          {step.questions.map((q) => (
            <li key={q}>{replaceClient(q, clientName)}</li>
          ))}
        </ul>
      )}

      {step.closingScript && (
        <div className="prep-pdf-quote">{replaceClient(step.closingScript, clientName)}</div>
      )}

      {step.kind === "executiveSummary" && step.validationQuestion && (
        <p className="prep-pdf-quote">
          Ask: &ldquo;{replaceClient(step.validationQuestion, clientName)}&rdquo;
        </p>
      )}
    </section>
  );
}
